import java.util.*;
import java.lang.*;
import java.io.*;

//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.


class AlgoPractice
{
	public static void main (String[] args) throws java.lang.Exception
	{
		String str1 = "hell";
		String str2 = "hello";
		char a = findTheDifference(str1, str2);
		System.out.println("The difference is " + a);
	}
	
	public static char findTheDifference(String s, String t){
	    int charCountS = 0;
	    int charCountT = 0;
	    for(int i =0; i<s.length(); i++){
	        charCountS = charCountS + (int)s.charAt(i);
	    }
	    for(int i =0; i<t.length(); i++){
	        charCountT = charCountT + (int)t.charAt(i);
	    }
	    return (char)(charCountT-charCountS);
	}
}
